version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11.8.0
        steps:
            - checkout
            - run: npm install
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run build
            - run: sudo apt-get update && sudo apt-get install -y python-dev
            - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
            - run: sudo python get-pip.py
            - run: sudo pip install awscli --upgrade
            - run: aws --version
            - run:
                name: Setup AWS credentials
                command: |
                    mkdir -p ~/.aws
                    printf "[default]\nregion = ${AWS_DEFAULT_REGION}\noutput = json" > ~/.aws/config
                    printf "[default]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/credentials
                    chmod 600 ~/.aws/*
            - run: aws s3 sync build/ s3://app.fxrapp.tk

